- name: nginx install and run
  hosts: web
  become: yes
  tasks:  

  - name: install nginx
    ansible.builtin.package: #if we use dnf means package other servers like ubuntu centose....called hetergenous
     name: nginx
     state: present 

  - name: run nginx
    ansible.builtin.service:
     name: nginx
     enabled: yes    
