- name: ngnix install and run
  hosts: web
  tasks: 
  become: yes
  - name: install ngnix
    ansible.builtin.package: #if we use dnf means package other servers like ubuntu centose....called hetergenous
    name: ngnix
    state: present 
