- name: variables to print
  hosts: web
  vars: 
   course: devops with AWS
   duration: 120 hours
   trainer: sivakumar reddy
  tasks: 
  - name: print the information
    ansible.builtin.debug:
     msg: "hi,iam learning {{course}},duration is : {{duration}},trainer is : {{trainer}}"

  - name: print the information and again
    vars:
     course: "ansible"
    ansible.builtin.debug:
      msg: "hi,iam learning {{course}},duration is : {{duration}},trainer is : {{trainer}}"

  - name: print the information and again again
    ansible.builtin.debug:
      msg: "hi,iam learning {{course}},duration is : {{duration}},trainer is : {{trainer}}"





      