- name: loops demo
  hosts: web
  become: yes
  tasks:
  - name: print the names
    ansible.builtin.package:
      name: "{{ items }}"
      state: present

    loop: 

    - mysql
    - nginx
    - postfix
    - httpd 