- name: demo on filters/functions
  hosts: local
  connection: local
  tasks: 
  - name: print the default variable
    ansible.builtin.debug:
     msg: "hello {{ course | default( 'ansible' ) }}"

  - name: convert to upper case
    var: 
     greeting: "hello ramesh"
    ansible.builtin.debug:
     msg: "{{ greeting | upper }}"

  - name: convert to lower case
    var: 
     greeting: "hello ramesh"
    ansible.builtin.debug:
     msg: "{{ greeting | lower }}"   